### ISSUE TITLE
How show initial image ?

### ISSUE THREAD

**Issue by joaolori** [ogix/ng2-fancy-image-uploader#16] opened 2018-03-14 08:06 UTC
Hello,

I would like to set image from model. something like this is possible?:

     <fancy-image-uploader [options]="options" (onUpload)="onUpload($event,'PosterThumbnail')" [ngsrc]="obj.PosterThumbnail"

But still able to click/drag to upload other image?

**Comment by ogix** [comment] 2018-03-14 18:58
Hello, this is duplicate of #15

**Closed as completed by ogix** 2018-03-14 18:58 UTC
Labels: duplicate
